In [1]:
import numpy as np

In [24]:
a=[[1,2,3],[4,5,6],[7,8,9]]
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [25]:
np.array(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
import torch

In [26]:
torch.Tensor(a)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [27]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [28]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [29]:
np.random.rand(2,2)

array([[0.53720681, 0.19566059],
       [0.76552398, 0.07939125]])

In [30]:
torch.rand(2,2)

tensor([[0.9417, 0.2292],
        [0.0063, 0.6658]])

In [31]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [33]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [35]:
np.random.rand(2,2)

array([[0.14675589, 0.09233859],
       [0.18626021, 0.34556073]])

In [36]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [37]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [38]:
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [40]:
if torch.cuda.is_available():
    print(1)
    torch.cuda.manual_seed_all(0)

1


In [41]:
a=np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [42]:
print(type(a))

<class 'numpy.ndarray'>


In [44]:
#Numpy to torch
torch_a=torch.from_numpy(a)
print(torch_a)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [50]:
a=np.ones((2,2),dtype=np.int64)
b=np.ones((2,3,2,1),dtype=np.int32)
c=np.ones((2,2),dtype=np.uint8)
d=np.ones((2,2),dtype=np.float64)
print(torch.from_numpy(a))
print(torch.from_numpy(b))
print(torch.from_numpy(c))
print(torch.from_numpy(d))

tensor([[1, 1],
        [1, 1]])
tensor([[[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]],


        [[[1],
          [1]],

         [[1],
          [1]],

         [[1],
          [1]]]], dtype=torch.int32)
tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [52]:
#Torch to Numpy
torch_a=torch.ones(2,2)
print(type(torch_a))
a=torch_a.numpy()
print(type(a))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [53]:
#Tensor on CPU
tcpu=torch.ones(3,3)

In [54]:
tcpu

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [55]:
#CPU to GPU
if torch.cuda.is_available():
    tcpu.cuda()

In [56]:
tcpu.cpu()

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [57]:
print(tcpu.size())

torch.Size([3, 3])


In [61]:
b=tcpu.numpy()
print(torch.from_numpy(b))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [69]:
tcpu.view(9)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [70]:
a=torch.ones(2,2)
b=torch.ones(2,2)
c=a+b
print(c)

tensor([[2., 2.],
        [2., 2.]])
